// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ValeControl.API.DbContexts;

#nullable disable

namespace ValeControl.API.Migrations
{
    [DbContext(typeof(ValeDbContext))]
    [Migration("20240513175718_NewMigration")]
    partial class NewMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ValeControl.API.Entities.EscalaTrabalho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EscalasTrabalho");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "5x2"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "6x1"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "6x2"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "12x36"
                        });
                });

            modelBuilder.Entity("ValeControl.API.Entities.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CustoDiario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EscalaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Funcionarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustoDiario = 50.00m,
                            EscalaId = 1,
                            Nome = "João Silva"
                        },
                        new
                        {
                            Id = 2,
                            CustoDiario = 60.00m,
                            EscalaId = 2,
                            Nome = "Maria Santos"
                        },
                        new
                        {
                            Id = 3,
                            CustoDiario = 70.00m,
                            EscalaId = 3,
                            Nome = "Pedro Oliveira"
                        },
                        new
                        {
                            Id = 4,
                            CustoDiario = 80.00m,
                            EscalaId = 4,
                            Nome = "Ana Costa"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
