// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ValeControl.API.DbContexts;

#nullable disable

namespace ValeControl.API.Migrations
{
    [DbContext(typeof(ValeDbContext))]
    [Migration("20240511140001_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ValeControl.API.Entities.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CustoDiario")
                        .HasColumnType("float");

                    b.Property<string>("EscalaDeTrabalho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Funcionarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustoDiario = 50.0,
                            EscalaDeTrabalho = "5x2",
                            Nome = "João Silva"
                        },
                        new
                        {
                            Id = 2,
                            CustoDiario = 60.0,
                            EscalaDeTrabalho = "6x1",
                            Nome = "Maria Santos"
                        },
                        new
                        {
                            Id = 3,
                            CustoDiario = 70.0,
                            EscalaDeTrabalho = "6x2",
                            Nome = "Pedro Oliveira"
                        },
                        new
                        {
                            Id = 4,
                            CustoDiario = 80.0,
                            EscalaDeTrabalho = "12x36",
                            Nome = "Ana Costa"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
