// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ValeControl.API.DbContexts;

#nullable disable

namespace ValeControl.API.Migrations
{
    [DbContext(typeof(ValeDbContext))]
    [Migration("20240517204933_UpdateFuncionarioEscalaEnum")]
    partial class UpdateFuncionarioEscalaEnum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ValeControl.API.Entities.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<decimal>("CustoDiario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Escala")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Funcionarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = false,
                            CustoDiario = 50.00m,
                            Escala = 1,
                            Nome = "João Silva"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = false,
                            CustoDiario = 60.00m,
                            Escala = 2,
                            Nome = "Maria Santos"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = false,
                            CustoDiario = 70.00m,
                            Escala = 3,
                            Nome = "Pedro Oliveira"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = false,
                            CustoDiario = 80.00m,
                            Escala = 4,
                            Nome = "Ana Costa"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
